version: "3.9"

services:
  xlog:
    platform: linux/amd64
    build:
        context: .
        args:
          TARGETOS: linux
          TARGETARCH: amd64
    image: xlog:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - XLOG_HTTP_ADDR=0.0.0.0:8888
      - XLOG_DUCKDB_PATH=/data/logs.duckdb
      - XLOG_LOG_TAIL=200
      - XLOG_LOG_SINCE=15m
    volumes:
      - ../xlog-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # demo:
  #   image: busybox:1.36
  #   restart: unless-stopped
  #   command: /bin/sh -c "i=0; while true; do echo \"demo log $${i}\"; >&2 echo \"error log $${i}\"; i=$$((i+1)); sleep 5; done"
